export const SET_CURRENT_YEAR = 'SET_CURRENT_YEAR';

export const GET_YEARS_START = 'GET_YEARS_START';
export const GET_YEARS_SUCCESS = 'GET_YEARS_SUCCESS';
export const GET_YEARS_FAILURE = 'GET_YEARS_FAILURE';