/** Coach Types */
const FETCHING_EXIT_TICKETS = 'FETCHING_EXIT_TICKETS';
const EXIT_TICKETS_RECEIVED = 'TICKETS_RECEIVED';
const SENDING_EXIT_TICKET = 'SENDING_EXIT_TICKET';
 
export default {
    FETCHING_EXIT_TICKETS,
    EXIT_TICKETS_RECEIVED,
    SENDING_EXIT_TICKET,
}