export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const GET_YEARS_START = 'GET_YEARS_START';
export const GET_YEARS_SUCCESS = 'GET_YEARS_SUCCESS';
export const GET_YEARS_FAILURE = 'GET_YEARS_FAILURE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_SORTED_USERS = 'SET_SORTED_USERS';
export const SET_PAGINATION_USERS = 'SET_PAGINATION_USERS';
export const SET_SEARCH_USERS = 'SET_SEARCH_USERS';