const GET_FORMS_START = 'FORMS/GET_EVENT_START';
const GET_FORMS_SUCCESS = 'FORMS/GET_FORM_SUCCESS';
const GET_FORMS_FAILURE = 'FORMS/GET_FORM_FAILURE';

const CREATE_FORM_START = 'FORMS/SET_FORM_START';
const CREATE_FORM_SUCCESS = 'FORMS/SET_FORM_SUCCESS';
const CREATE_FORM_FAILURE = 'FORMS/SET_FORM_FAILURE';

const DELETE_FORM_START = 'FORMS/DELETE_FORM_START';
const DELETE_FORM_SUCCESS = 'FORMS/DELETE_FORM_SUCCESS';
const DELETE_FORM_FAILURE = 'FORMS/DELETE_FORM_FAILURE';

const UPDATE_FORM_START = 'FORMS/UPDATE_FORM_START';
const UPDATE_FORM_SUCCESS = 'FORMS/UPDATE_FORM_SUCCESS';
const UPDATE_FORM_FAILURE = 'FORMS/UPDATE_FORM_FAILURE';

const ASSIGN_FORM_START = 'FORMS/ASSIGN_FORM_START';
const ASSIGN_FORM_SUCCESS = 'FORMS/ASSIGN_FORM_SUCCESS';
const ASSIGN_FORM_FAILURE = 'FORMS/ASSIGN_FORM_FAILURE';

const SET_CURRENT_FORM = 'FORMS/SET_CURRENT_FORM';

export default {
    GET_FORMS_START,
    GET_FORMS_SUCCESS,
    GET_FORMS_FAILURE,
    CREATE_FORM_START,
    CREATE_FORM_SUCCESS,
    CREATE_FORM_FAILURE,
    DELETE_FORM_START,
    DELETE_FORM_SUCCESS,
    DELETE_FORM_FAILURE,
    UPDATE_FORM_START,
    UPDATE_FORM_SUCCESS,
    UPDATE_FORM_FAILURE,
    ASSIGN_FORM_START,
    ASSIGN_FORM_SUCCESS,
    ASSIGN_FORM_FAILURE,
    SET_CURRENT_FORM,
}