const LOGIN_USER_START = 'LOGIN_USER_START';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

const AUTHENTICATE_USER_START = 'AUTHENTICATE_USER_START';
const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE';

const LOGOUT_USER_START = 'LOGOUT_USER_START';
const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

const FORGOT_PW_START = 'FORGOT_PW_START';
const FORGOT_PW_SUCCESS = 'FORGOT_PW_SUCCESS';
const FORGOT_PW_FAILURE = 'FORGOT_PW_FAILURE';

export default {
    LOGIN_USER_START,
    LOGIN_USER_SUCCESS,
    LOGIN_USER_FAILURE,
    AUTHENTICATE_USER_START,
    AUTHENTICATE_USER_SUCCESS,
    AUTHENTICATE_USER_FAILURE,
    LOGOUT_USER_START,
    LOGOUT_USER_SUCCESS,
    LOGOUT_USER_FAILURE,
    FORGOT_PW_START,
    FORGOT_PW_SUCCESS,
    FORGOT_PW_FAILURE
}