/** Types for Sessions */

const DELETING_SESSION = 'DELETING_SESSION';
const SESSION_DELETED = 'SESSION_DELETED';
const ADDING_SESSION = 'ADDING_SESSION';
const SESSION_ADDED = 'SESSION_ADDED';
const UPDATING_SESSION = 'UPDATING_SESSION';
const SESSION_UPDATED = 'SESSION_UPDATED';
// fetching sessions is in the admin redux duck

export default {
    DELETING_SESSION,
    SESSION_DELETED,
    ADDING_SESSION,
    SESSION_ADDED,
    UPDATING_SESSION,
    SESSION_UPDATED,
}