/** Types for App Authentication */

const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
const LOGGED_OUT = 'LOGGED_OUT';
const SET_USER = 'SET_USER';
const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

export default {
    AUTHENTICATE_USER,
    LOGGED_OUT,
    SET_USER,
    USER_AUTHENTICATED,
}