export const GET_EVENT_START = 'Events/GET_EVENT_START';
export const GET_EVENT_SUCCESS = 'Events/GET_EVENT_SUCCESS';
export const GET_EVENT_FAILURE = 'Events/GET_EVENT_FAILURE';

export const CREATE_EVENT_START = 'Events/SET_EVENT_START';
export const CREATE_EVENT_SUCCESS = 'Events/SET_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'Events/SET_EVENT_FAILURE';

export const DELETE_EVENT_START = 'Events/DELETE_EVENT_START';
export const DELETE_EVENT_SUCCESS = 'Events/DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'Events/DELETE_EVENT_FAILURE';

const UPDATE_EVENT_START = 'Events/UPDATE_EVENT_START';
const UPDATE_EVENT_SUCCESS = 'Events/UPDATE_EVENT_SUCCESS';
const UPDATE_EVENT_FAILURE = 'Events/UPDATE_EVENT_FAILURE';

export default {
    GET_EVENT_START,
    GET_EVENT_SUCCESS,
    GET_EVENT_FAILURE,
    CREATE_EVENT_START,
    CREATE_EVENT_SUCCESS,
    CREATE_EVENT_FAILURE,
    DELETE_EVENT_START,
    DELETE_EVENT_SUCCESS,
    DELETE_EVENT_FAILURE,
    UPDATE_EVENT_START,
    UPDATE_EVENT_SUCCESS,
    UPDATE_EVENT_FAILURE
}