export const GET_TICKETS_START = 'GET_TICKETS_START';
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKETS_FAILURE = 'GET_TICKETS_FAILURE';

export const UPDATE_TICKET_START = 'UPDATE_TICKET_START';
export const UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS';
export const UPDATE_TICKET_FAILURE = 'UPDATE_TICKET_FAILURE';

export const DELETE_TICKET_START = 'DELETE_TICKET_START';
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS';
export const DELETE_TICKET_FAILURE = 'DELETE_TICKET_FAILURE';

export const SET_CURRENT_TICKET = 'SET_CURRENT_TICKET';
export const SET_SORTED_TICKETS = 'SET_SORTED_TICKETS';
export const SET_PAGINATION_TICKETS = 'SET_PAGINATION_TICKETS';
export const SET_SEARCH_TICKETS = 'SET_SEARCH_TICKETS';