const GET_SESSIONS_START = 'SESSIONS/GET_SESSIONS_START';
const GET_SESSIONS_SUCCESS = 'SESSIONS/GET_SESSIONS_SUCCESS';
const GET_SESSIONS_FAILURE = 'SESSIONS/GET_SESSIONS_FAILURE';

const CREATE_SESSION_START = 'SESSIONS/CREATE_SESSION_START';
const CREATE_SESSION_SUCCESS = 'SESSIONS/CREATE_SESSION_SUCCESS';
const CREATE_SESSION_FAILURE = 'SESSIONS/CREATE_SESSION_FAILURE';

const DELETE_SESSION_START = 'SESSIONS/DELETE_SESSION_START';
const DELETE_SESSION_SUCCESS = 'SESSIONS/DELETE_SESSION_SUCCESS';
const DELETE_SESSION_FAILURE = 'SESSIONS/DELETE_SESSION_FAILURE';

const UPDATE_SESSION_START = 'SESSIONS/UPDATE_SESSION_START';
const UPDATE_SESSION_SUCCESS = 'SESSIONS/UPDATE_SESSION_SUCCESS';
const UPDATE_SESSION_FAILURE = 'SESSIONS/UPDATE_SESSION_FAILURE';

const SET_CURRENT_SESSION = 'SESSIONS/SET_CURRENT_SESSION'

export default {
    GET_SESSIONS_START,
    GET_SESSIONS_SUCCESS,
    GET_SESSIONS_FAILURE,
    CREATE_SESSION_START,
    CREATE_SESSION_SUCCESS,
    CREATE_SESSION_FAILURE,
    DELETE_SESSION_START,
    DELETE_SESSION_SUCCESS,
    DELETE_SESSION_FAILURE,
    UPDATE_SESSION_START,
    UPDATE_SESSION_SUCCESS,
    UPDATE_SESSION_FAILURE,
    SET_CURRENT_SESSION,
}