/** Coach Types */
const GET_TICKETS_START = 'COACH/GET_TICKETS_START';
const GET_TICKETS_SUCCESS = 'COACH/GET_TICKETS_SUCCESS';
const GET_TICKETS_FAILURE = 'COACH/GET_TICKETS_FAILURE';

const SUBMIT_TICKET_START = 'COACH/SUBMIT_TICKET_START';
const SUBMIT_TICKET_SUCCESS = 'COACH/SUBMIT_TICKET_SUCCESS';
const SUBMIT_TICKET_FAILURE = 'COACH/SUBMIT_TICKET_FAILURE';

const GET_COMPLETED_START = 'GET_COMPLETED_START';
const GET_COMPLETED_SUCCESS = 'GET_COMPLETED_SUCCESS';
const GET_COMPLETED_FAILURE = 'GET_COMPLETED_FAILURE';

const SET_OPEN_TICKETS = 'SET_OPEN_TICKETS';
const SET_CURRENT_TICKET = 'SET_CURRENT_TICKET';

 
export default {
    GET_TICKETS_START,
    GET_TICKETS_SUCCESS,
    GET_TICKETS_FAILURE,
    SUBMIT_TICKET_START,
    SUBMIT_TICKET_SUCCESS,
    SUBMIT_TICKET_FAILURE,
    GET_COMPLETED_START,
    GET_COMPLETED_SUCCESS,
    GET_COMPLETED_FAILURE,
    SET_OPEN_TICKETS,
    SET_CURRENT_TICKET,
}