/** Types for Admin */

const FETCHING_EVENTS = 'FETCH_EVENTS';
const FETCHING_FORMS = 'FETCH_FORMS';
const FETCHING_SESSIONS = 'FETCH_SESSIONS';
const FETCHING_TICKETS = 'FETCHING_TICKETS';
const FETCHING_USERS = 'FETCH_USERS';
const FETCHING_YEARS = 'FETCH_YEARS';
const EVENTS_RECEIVED = 'EVENTS_RECEIVED';
const FORMS_RECEIVED = 'FORMS_RECEIVED';
const SESSIONS_RECEIVED = 'SESSIONS_RECEIVED';
const TICKETS_RECEIVED = 'TICKETS_RECEIVED';
const USERS_RECEIVED = 'USERS_RECEIVED';
const YEARS_RECEIVED = 'YEARS_RECEIVED';

export default {
    FETCHING_EVENTS,
    FETCHING_FORMS,
    FETCHING_SESSIONS,
    FETCHING_TICKETS,
    FETCHING_USERS,
    FETCHING_YEARS,
    EVENTS_RECEIVED,
    FORMS_RECEIVED,
    SESSIONS_RECEIVED,
    TICKETS_RECEIVED,
    USERS_RECEIVED,
    YEARS_RECEIVED,
}